spring.application.name=API-GATEWAY
server.port=8080

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable automatic service discovery routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# JWT Configuration
jwt.secret=mysupersecurejwtsecretkeymysupersecurejwt123
jwt.expiration=3600000

# -------------------------
# Gateway Routes
# -------------------------

# Employee Service Route
spring.cloud.gateway.routes[0].id=employee-service
spring.cloud.gateway.routes[0].uri=lb://EMPLOYEE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/employee/**

# Department Service Route
spring.cloud.gateway.routes[1].id=department-service
spring.cloud.gateway.routes[1].uri=lb://DEPARTMENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/department/**

# Payroll Service Route
spring.cloud.gateway.routes[2].id=payroll-service
spring.cloud.gateway.routes[2].uri=lb://PAYROLL-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/payroll/**
