spring.application.name=PAYROLL-SERVICE
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Circuit Breaker for Employee Service
resilience4j.circuitbreaker.instances.employeeService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.employeeService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.employeeService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.employeeService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.employeeService.registerHealthIndicator=true

# Circuit Breaker for Department Service
resilience4j.circuitbreaker.instances.departmentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.departmentService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.departmentService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.departmentService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.departmentService.registerHealthIndicator=true
